
name: PokeFarmQoL verification workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - .*
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "10.19.0"
        
    - name: npm install
      run: npm install -g npm@7.6.1
      
    - name: npm test
      run: |
        npm run sanctioned_test
        npm run user_test
        npm test
      env:
        CI: true
